/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ProjectStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'adopted' : IDL.Null,
});
export const Time = IDL.Int;
export const HandoverType = IDL.Variant({
  'fullAdoption' : IDL.Null,
  'equityPartnership' : IDL.Null,
  'codeSwap' : IDL.Null,
});
export const GithubId = IDL.Text;
export const Project = IDL.Record({
  'id' : IDL.Nat,
  'status' : ProjectStatus,
  'title' : IDL.Text,
  'createdAt' : Time,
  'repoUrl' : IDL.Text,
  'pitch' : IDL.Text,
  'handoverType' : HandoverType,
  'submitterGithubId' : GithubId,
  'techStack' : IDL.Vec(IDL.Text),
});
export const UserProfile = IDL.Record({
  'githubId' : GithubId,
  'githubUsername' : IDL.Text,
  'githubAvatarUrl' : IDL.Text,
});
export const Proposal = IDL.Record({
  'id' : IDL.Nat,
  'proposerGithubId' : GithubId,
  'createdAt' : Time,
  'projectId' : IDL.Nat,
  'message' : IDL.Text,
});
export const User = IDL.Record({
  'createdAt' : Time,
  'githubId' : GithubId,
  'githubUsername' : IDL.Text,
  'githubAvatarUrl' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'connectUser' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getApprovedProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getProjectById' : IDL.Func([IDL.Nat], [IDL.Opt(Project)], ['query']),
  'getProposalsByProject' : IDL.Func([IDL.Nat], [IDL.Vec(Proposal)], ['query']),
  'getStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'inAudit' : IDL.Nat,
          'listed' : IDL.Nat,
          'adopted' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getUserByGithubId' : IDL.Func([GithubId], [IDL.Opt(User)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitProject' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text, IDL.Text, GithubId],
      [IDL.Nat],
      [],
    ),
  'submitProposal' : IDL.Func([IDL.Nat, GithubId, IDL.Text], [IDL.Nat], []),
  'updateProjectStatus' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ProjectStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'adopted' : IDL.Null,
  });
  const Time = IDL.Int;
  const HandoverType = IDL.Variant({
    'fullAdoption' : IDL.Null,
    'equityPartnership' : IDL.Null,
    'codeSwap' : IDL.Null,
  });
  const GithubId = IDL.Text;
  const Project = IDL.Record({
    'id' : IDL.Nat,
    'status' : ProjectStatus,
    'title' : IDL.Text,
    'createdAt' : Time,
    'repoUrl' : IDL.Text,
    'pitch' : IDL.Text,
    'handoverType' : HandoverType,
    'submitterGithubId' : GithubId,
    'techStack' : IDL.Vec(IDL.Text),
  });
  const UserProfile = IDL.Record({
    'githubId' : GithubId,
    'githubUsername' : IDL.Text,
    'githubAvatarUrl' : IDL.Text,
  });
  const Proposal = IDL.Record({
    'id' : IDL.Nat,
    'proposerGithubId' : GithubId,
    'createdAt' : Time,
    'projectId' : IDL.Nat,
    'message' : IDL.Text,
  });
  const User = IDL.Record({
    'createdAt' : Time,
    'githubId' : GithubId,
    'githubUsername' : IDL.Text,
    'githubAvatarUrl' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'connectUser' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getApprovedProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getProjectById' : IDL.Func([IDL.Nat], [IDL.Opt(Project)], ['query']),
    'getProposalsByProject' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Proposal)],
        ['query'],
      ),
    'getStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'inAudit' : IDL.Nat,
            'listed' : IDL.Nat,
            'adopted' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getUserByGithubId' : IDL.Func([GithubId], [IDL.Opt(User)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitProject' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text, IDL.Text, GithubId],
        [IDL.Nat],
        [],
      ),
    'submitProposal' : IDL.Func([IDL.Nat, GithubId, IDL.Text], [IDL.Nat], []),
    'updateProjectStatus' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };