/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type GithubId = string;
export type HandoverType = { 'fullAdoption' : null } |
  { 'equityPartnership' : null } |
  { 'codeSwap' : null };
export interface Project {
  'id' : bigint,
  'status' : ProjectStatus,
  'title' : string,
  'createdAt' : Time,
  'repoUrl' : string,
  'pitch' : string,
  'handoverType' : HandoverType,
  'submitterGithubId' : GithubId,
  'techStack' : Array<string>,
}
export type ProjectStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'adopted' : null };
export interface Proposal {
  'id' : bigint,
  'proposerGithubId' : GithubId,
  'createdAt' : Time,
  'projectId' : bigint,
  'message' : string,
}
export type Time = bigint;
export interface User {
  'createdAt' : Time,
  'githubId' : GithubId,
  'githubUsername' : string,
  'githubAvatarUrl' : string,
}
export interface UserProfile {
  'githubId' : GithubId,
  'githubUsername' : string,
  'githubAvatarUrl' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'connectUser' : ActorMethod<[string, string, string], undefined>,
  'getAllProjects' : ActorMethod<[], Array<Project>>,
  'getApprovedProjects' : ActorMethod<[], Array<Project>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getProjectById' : ActorMethod<[bigint], [] | [Project]>,
  'getProposalsByProject' : ActorMethod<[bigint], Array<Proposal>>,
  'getStats' : ActorMethod<
    [],
    { 'inAudit' : bigint, 'listed' : bigint, 'adopted' : bigint }
  >,
  'getUserByGithubId' : ActorMethod<[GithubId], [] | [User]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitProject' : ActorMethod<
    [string, string, Array<string>, string, string, GithubId],
    bigint
  >,
  'submitProposal' : ActorMethod<[bigint, GithubId, string], bigint>,
  'updateProjectStatus' : ActorMethod<[bigint, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];